### ISSUE TITLE
请问下如何配置

### ISSUE THREAD

**Issue by sephrioth** [fineemb/Colorfulclouds-weather#1]
已经通过 HACS 安装完毕，但是没有找到配置入口?

**Comment by plutosherry** [comment]
The same problems.....

**Comment by fineemb** [comment]
配置-集成-右下角＋

**Comment by sephrioth** [comment]
> 配置-集成-右下角＋

并没有?
![image](https://user-images.githubusercontent.com/4231328/95612680-5f967480-0a96-11eb-9e9f-cfb3b23cd6ac.png)
