### ISSUE TITLE
Reported "Unknown error occurred"

### ISSUE THREAD

**Issue by UJStudio** [fineemb/Colorfulclouds-weather#11]
Hass Core 2021.4.0.dev0
Frontend 20210330.0 - latest

Error details reference to attachments.

[colorfulclouds_error.log](https://github.com/fineemb/Colorfulclouds-weather/files/6235919/colorfulclouds_error.log)
![colorfulclouds_error](https://user-images.githubusercontent.com/18565537/113131460-d5161d00-924f-11eb-9aea-b9b0c781d43a.png)

**Comment by hawnei0708** [comment]
升级到2021.4.0后同样的问题

**Comment by fineemb** [comment]
v1.2.5 修复这个问题, 如有问题请重新开启

**Comment by UJStudio** [comment]
v1.2.5 work perfect!
