### ISSUE TITLE
日出日落时间显示错误

### ISSUE THREAD

**Issue by muxiachuixue** [fineemb/Colorfulclouds-weather#15]
HA版本：2021.11.5   supervised 版
是否有彩云key：是
是否安装最新彩云天气插件：是
时区是否正确：是，上海时区
GPS信息是否填写正确：是，为上海这边经纬度
其他信息是否显示正确：是

问题：
彩云卡片中日出时间显示为：“下午3:19:29”，日落时间显示为“下午11:36:36”，且第二天还是会显示错

尝试过用postman直接访问彩云API，返回信息中可以看到正确的日出日落时间，不知是否是HA版本太新，和彩云插件代码有冲突的原因？

**Comment by fineemb** [comment]
日出日落用的hass自己的
