### ISSUE TITLE
关于适配Home Assistant 2022.3.0

### ISSUE THREAD

**Issue by yyxp1989** [fineemb/Colorfulclouds-weather#18]
记录器：homeassistant.helpers.entity
来源：helpers/entity.py:574 第一次发生： 22:47: 24 （10次） 最后记录： 22:47: 24

实体 sensor.home_shu_gua_zhi_shu (<class 'custom_components.colorfulclouds.sensor.ColorfulcloudsSensor'>) 实现了 device_state_attributes。请向自定义组件作者报告。
实体 sensor.home_zi_wai_xian (<class 'custom_components.colorfulclouds.sensor.ColorfulcloudsSensor'>) 实现了 device_state_attributes。请向自定义组件作者报告。
实体 sensor.home_shi_du (<class 'custom_components.colorfulclouds.sensor.ColorfulcloudsSensor'>) 实现 device_state_attributes。请向自定义组件作者报告。
实体 sensor.home_neng_jian_du (<class 'custom_components.colorfulclouds.sensor.ColorfulcloudsSensor'>) 实现了 device_state_attributes。请向自定义组件作者报告。
实体 sensor.home_feng_su (<class 'custom_components.colorfulclouds.sensor.ColorfulcloudsSensor'>) 实现 device_state_attributes。请向自定义组件作者报告。

**Comment by Soolita** [comment]
2022-02-16 15:46:30 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.wo_de_jia_gan_jue_wen_du (<class 'custom_components.colorfulclouds.sensor.ColorfulcloudsSensor'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-16 15:46:30 WARNING (MainThread) [homeassistant.helpers.frame] Detected code that uses str for device registry entry_type. This is deprecated and will stop working in Home Assistant 2022.3, it should be updated to use DeviceEntryType instead. Please report this issue.

**Comment by Soolita** [comment]
现在是一堆警告，估计2022.3会不可用了

**Comment by neckyaan** [comment]
1.修改homeassistant\custom_components\colorfulclouds\sensor.py和weather.py这两个文件，将entry_type替换为DeviceEntryType
2.homeassistant\custom_components\colorfulclouds\sensor.py这个文件修改，将device_state_attributes替换为extra_state_attributes

3.作者长时间报没有维护了，大家自己修改吧。完美解决以上几个错的地方。

**Comment by neckyaan** [comment]
@property
    def device_info(self):
        """Return the device info."""
        return {
            "identifiers": {(DOMAIN, self.coordinator.data["location_key"])},
            "name": self._name,
            "manufacturer": MANUFACTURER,
            "DeviceEntryType": "service",
        }

**Comment by neckyaan** [comment]
@property
    def extra_state_attributes(self):
        """Return the state attributes."""
        # if self.forecast_day is not None:
        #     if self.kind in ["WindGustDay", "WindGustNight"]:
        #         self._attrs["direction"] = self.coordinator.data.data[ATTR_FORECAST][
        #             self.forecast_day
        #         ][self.kind]["Direction"]["English"]

**Comment by neckyaan** [comment]
已提交Pull requests，大家可看下。

**Comment by fineemb** [comment]
已Merged
感谢，最近有点忙
