### ISSUE TITLE
报错日志

### ISSUE THREAD

**Issue by hn315** [fineemb/Colorfulclouds-weather#19]
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:583
First occurred: 2022年2月21日 19:20:46 (13 occurrences)
Last logged: 2022年2月21日 19:20:47

Entity sensor.wo_de_jia_zi_wai_xian (<class 'custom_components.colorfulclouds.sensor.ColorfulcloudsSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.wo_de_jia_shi_du (<class 'custom_components.colorfulclouds.sensor.ColorfulcloudsSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.wo_de_jia_neng_jian_du (<class 'custom_components.colorfulclouds.sensor.ColorfulcloudsSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.wo_de_jia_feng_su (<class 'custom_components.colorfulclouds.sensor.ColorfulcloudsSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.wo_de_jia_feng_xiang (<class 'custom_components.colorfulclouds.sensor.ColorfulcloudsSensor'>) implements device_state_attributes. Please report it to the custom component author.

**Comment by fineemb** [comment]
已Merged
