### ISSUE TITLE
请问如何UI配置

### ISSUE THREAD

**Issue by duchenpaul** [fineemb/Colorfulclouds-weather#3]
在HACS和intergation里面没有发现ui界面

Version
```
Home Assistant: 0.116.2
HACS: 1.6.0
Colorfulclouds-weather: master version
```

**Comment by NathanDai** [comment]
同样发现没法集成 提交了配置文件ui页面无法加载
![image](https://user-images.githubusercontent.com/28701315/96839030-33f29180-147b-11eb-9217-c3dc17cd6a8f.png)

**Comment by fineemb** [comment]
按照提示去装

**Comment by Mybrc91** [comment]
> 在HACS和intergation里面没有发现ui界面
> 
> Version
> 
> ```
> Home Assistant: 0.116.2
> HACS: 1.6.0
> Colorfulclouds-weather: master version
> ```

配置-集成-右下角+-搜索“colorfulclouds”

**Comment by mmycjguo** [comment]
插件安装了，但不知怎么设置，KEY填哪，集成是指HA下的集成，还是HAC处的集成，

**Comment by Mybrc91** [comment]
> 插件安装了，但不知怎么设置，KEY填哪，集成是指HA下的集成，还是HAC处的集成，

配置-集成-右下角+搜索“colorfulclouds”

**Comment by duchenpaul** [comment]
找到了, 藏得好深.
我还是习惯写config

1. 增加entity
![1](https://user-images.githubusercontent.com/8120099/97827129-59469180-1cfe-11eb-9486-311356e9ef8b.png)

2. 配置
![2](https://user-images.githubusercontent.com/8120099/97827133-5cda1880-1cfe-11eb-9de5-da7111bd02df.png)

**Comment by xuexijiaoben** [comment]
谢谢啦，搞了半天，是这么装，对小白来说太难找了
