### ISSUE TITLE
大佬，能给彩云天气新增一个降雨预警实体嘛？string做状态也行

### ISSUE THREAD

**Issue by liudab** [fineemb/Colorfulclouds-weather#31]
搞彩云一大目的就是为了降雨预警，现在的实体体现不出这个功能，都是温度湿度之类的。
其实也就是openweather和accuweather都能做的。
我看HACS前端能够正常显示降雨预警状态：“未来两小时不会下雨，请放心出门吧”
能不能搞个实体专门体现这个文字报告？这个HACS的代码我不清楚怎么搞？
大佬json解析添加一个解析器？加个文字输出实体？
这样就可以实现下雨前提前微信提醒等等功能了。

**Comment by fineemb** [comment]
仔细看输出属性。都有
