### ISSUE TITLE
hass日志报警

### ISSUE THREAD

**Issue by neckyaan** [fineemb/Colorfulclouds-weather#32]
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:77
First occurred: 13:31:16 (2 occurrences)
Last logged: 13:31:16

Detected integration that accesses the `is_metric` property of the unit system. This is deprecated and will stop working in Home Assistant 2023.1. Please adjust to use instance check instead.. Please report issue to the custom integration author for colorfulclouds using this method at custom_components/colorfulclouds/__init__.py, line 129: self.is_metric = hass.config.units.is_metric
Detected integration that accesses the `is_metric` property of the unit system. This is deprecated and will stop working in Home Assistant 2023.1. Please adjust to use instance check instead.. Please report issue to the custom integration author for colorfulclouds using this method at custom_components/colorfulclouds/__init__.py, line 130: if hass.config.units.is_metric:

记录器：homeassistant.helpers.frame
来源：helpers/frame.py:77
首次出现：13:31:16（2 次出现）
最后登录时间：13:31:16

检测到访问单位系统的“is_metric”属性的集成。 这已被弃用，并将停止在 Home Assistant 2023.1 中工作。 请调整以改用实例检查。请在 custom_components/colorfulclouds/__init__.py 第 129 行使用此方法向 colourclouds 的自定义集成作者报告问题：self.is_metric = hass.config.units.is_metric
检测到访问单位系统的“is_metric”属性的集成。 这已被弃用，并将停止在 Home Assistant 2023.1 中工作。 请调整以改用实例检查。请在 custom_components/colorfulclouds/__init__.py 第 130 行使用此方法向 colourclouds 的自定义集成作者报告问题：如果 hass.config.units.is_metric：

Logger: homeassistant.components.weather
Source: components/weather/__init__.py:199
Integration: Weather ([documentation](https://www.home-assistant.io/integrations/weather), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+weather%22))
First occurred: 13:31:18 (1 occurrences)
Last logged: 13:31:18

custom_components.colorfulclouds.weather::ColorfulCloudsEntity is overriding deprecated methods on an instance of WeatherEntity, this is not valid and will be unsupported from Home Assistant 2023.1. Please report it to the custom integration author.

记录器：homeassistant.components.weather
来源：组件/天气/__init__.py:199
集成：天气（文档、问题）
第一次发生：13:31:18（1 次）
最后登录时间：13:31:18

custom_components.colorfulclouds.weather::ColorfulCloudsEntity 正在覆盖 WeatherEntity 实例上不推荐使用的方法，这是无效的，并且将不受 Home Assistant 2023.1 的支持。 请将其报告给自定义集成作者。

**Comment by mzfe** [comment]
HA总是改来改去。

**Comment by sephrioth** [comment]
马上就到2023年了，麻烦作者有空的话关注下...
