### ISSUE TITLE
ha升级到2023.8后无法使用

### ISSUE THREAD

**Issue by chenjiezb** [fineemb/Colorfulclouds-weather#45]
HA升级到2023.8后，仪表板上无法正常显示，实体全部变为不可用。
Logger: homeassistant.components.weather
Source: components/weather/__init__.py:169
Integration: 天气 (documentation, issues)
First occurred: 01:17:14 (1 occurrences)
Last logged: 01:17:14

custom_components.colorfulclouds.weather::ColorfulCloudsEntity is overriding deprecated methods on an instance of WeatherEntity, this is not valid and will be unsupported from Home Assistant 2023.1. Please report it to the custom integration author.

**Comment by fineemb** [comment]
更新到v2.0.0
