### ISSUE TITLE
Home Assistant 2023.8.3 无法使用

### ISSUE THREAD

**Issue by catchfishday** [fineemb/Colorfulclouds-weather#46]
Home Assistant 2023.8.3
Supervisor 2023.08.1
前端版本： 20230802.1 - latest

stderr: [31m2023-08-19 09:42:24.515 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform colorfulclouds
stderr: Traceback (most recent call last):
stderr:   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in async_add_entities
stderr:     await asyncio.gather(*tasks)
stderr:   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 750, in _async_add_entity
stderr:     await entity.add_to_platform_finish()
stderr:   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1004, in add_to_platform_finish
stderr:     self.async_write_ha_state()
stderr:   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 746, in async_write_ha_state
stderr:     self._async_write_ha_state()
stderr:   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 808, in _async_write_ha_state
stderr:     state = self._stringify_state(available)
stderr:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
stderr:   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 752, in _stringify_state
stderr:     if (state := self.state) is None:
stderr:                  ^^^^^^^^^^
stderr:   File "/config/custom_components/colorfulclouds/sensor.py", line 120, in state
stderr:     return self.coordinator.data["result"]["realtime"][self.kind]

**Comment by catchfishday** [comment]
，，，彩云天气api需要充值了

**Comment by fineemb** [comment]
更新到v2.0.0
