### ISSUE TITLE
API要收费了，怎样限制调用频率？

### ISSUE THREAD

**Issue by MX10085** [fineemb/Colorfulclouds-weather#47]
最近收到邮件，提示9月份取消免费调用API，怎样限制调用频率？

**Comment by georgezhao2010** [comment]
同上，虽然知道可以手动改代码实现调用频率的调整，但建议添加configure项来控制调用频率。

**Comment by MX10085** [comment]
> 同上，虽然知道可以手动改代码实现调用频率的调整，但建议添加configure项来控制调用频率。

请问一下改动代码那个地方可以实现呢？

**Comment by sephrioth** [comment]
> > 同上，虽然知道可以手动改代码实现调用频率的调整，但建议添加configure项来控制调用频率。
> 
> 请问一下改动代码那个地方可以实现呢？

__init__.py 文件下有个  datetime.timedelta(minutes=6)  ，当前是6分钟更新一次

**Comment by MX10085** [comment]
> > > 同上，虽然知道可以手动改代码实现调用频率的调整，但建议添加configure项来控制调用频率。
> > 
> > 
> > 请问一下改动代码那个地方可以实现呢？
> 
> **init**.py 文件下有个 datetime.timedelta(minutes=6) ，当前是6分钟更新一次

多谢啦！

**Comment by supern001** [comment]
> > > 同上，虽然知道可以手动改代码实现调用频率的调整，但建议添加configure项来控制调用频率。
> > 
> > 
> > 请问一下改动代码那个地方可以实现呢？
> 
> **init**.py 文件下有个 datetime.timedelta(minutes=6) ，当前是6分钟更新一次

多谢多谢。算了下，设置52.56分钟更新一次，一年刚好10000万次:P

**Comment by GOUKI9999** [comment]
请问一下，我已经更新了这里为60，现在看还是每小时更新10次是为什么呢

**Comment by Hugh696** [comment]
提供一个好方法，Home Assistant里的数据我基本不会进去看，所以它更不更新无所谓，随便设个120min。但是我做了语音播报，按下无线按键后，重载一下插件，此时数据就是最新的，然后再播报出来

**Comment by fineemb** [comment]
更新到v2.0.0
