### ISSUE TITLE
想问下大佬后续是否还有维护的计划？同时想问下大家是否有平替方案。

### ISSUE THREAD

**Issue by onecombo** [fineemb/Colorfulclouds-weather#49]
在此十分感谢开发者大佬长期以来的开发维护。

**Comment by zealotCE** [comment]
https://github.com/hasscc/tianqi
看看这个项目？

**Comment by onecombo** [comment]
> https://github.com/hasscc/tianqi 看看这个项目？

感谢

**Comment by andykeppel** [comment]
> https://github.com/hasscc/tianqi 看看这个项目？

感谢感谢，不过装了之后不知道这个服务器域应该填什么
![image](https://github.com/fineemb/Colorfulclouds-weather/assets/62137704/59a51b44-3b68-4350-b405-88a617d7fec5)

**Comment by zealotCE** [comment]
> andykeppel

服务器域：weather.com.cn
搜索地点：先输入你对应的城市（其实其他的也可以，然后就会出现使用家庭经纬度的选项了，我用的是自己的经纬度）

**Comment by andykeppel** [comment]
> > andykeppel
> 
> 服务器域：weather.com.cn 搜索地点：先输入你对应的城市（其实其他的也可以，然后就会出现使用家庭经纬度的选项了，我用的是自己的经纬度）

太感谢了！

**Comment by fineemb** [comment]
更新到v2.0.0
