### ISSUE TITLE
此项在版本 2024.3.0 中无法工作。请在升级之前解决。

### ISSUE THREAD

**Issue by tfkzptzt** [fineemb/Colorfulclouds-weather#50]
Home Assistant给出的警告

The colorfulclouds integration is using deprecated forecast
此项在版本 2024.3.0 中无法工作。请在升级之前解决。
The integration colorfulclouds is using the deprecated forecast attribute.
Please report it to the custom integration author..

![image](https://github.com/fineemb/Colorfulclouds-weather/assets/53414921/b4315d3b-399e-4639-9ac4-acde9e54771c)

**Comment by cnzhenghao** [comment]
我也是这个提示，官方也没个回复？

**Comment by wuzhijian287** [comment]
我也是这个提示，官方也没个回复？

**Comment by xinghusp** [comment]
需要做修改了，说明如下：
https://developers.home-assistant.io/blog/2023/08/07/weather_entity_forecast_types/
https://developers.home-assistant.io/docs/core/entity/weather/#weather-forecasts

作者大大还计划维护嘛？

**Comment by fineemb** [comment]
更新到v2.0.0
