### ISSUE TITLE
我充值后，怎么能再次上线，目前进行重载后还是未响应

### ISSUE THREAD

**Issue by KNXer50520** [fineemb/Colorfulclouds-weather#51]
![image](https://github.com/fineemb/Colorfulclouds-weather/assets/50094752/a626934b-a5fe-4da3-86ef-209c59c5c8a7)

**Comment by jerry2022** [comment]
你全选以后先禁用，过一会再启用就好了

**Comment by fineemb** [comment]
更新到v2.0.0
