### ISSUE TITLE
创建错误报告

### ISSUE THREAD

**Issue by neckyaan** [fineemb/Colorfulclouds-weather#52]
DEVICE_CLASS_TEMPERATURE是从colorfulclouds使用的，这是一个已弃用的常量，将在HA Core 2025.1中删除。 请改用 SensorDeviceClass.TEMPERATURE，请在 https://github.com/fineemb/Colorfulclouds-weather/issues 创建错误报告
TEMP_CELSIUS 是从 colorfulclouds 中使用的，这是一个已弃用的常量，将在 HA Core 2025.1 中删除。 请改用 UnitOfTemperature.CELSIUS，请在 https://github.com/fineemb/Colorfulclouds-weather/issues 创建错误报告
TEMP_FAHRENHEIT 是从 colorfulclouds 使用的，这是一个已弃用的常量，将在 HA Core 2025.1 中删除。 请使用 UnitOfTemperature.FAHRENHEIT 代替，请在 https://github.com/fineemb/Colorfulclouds-weather/issues 创建错误报告

**Comment by jammy1992** [comment]
一样的，一直提示天气实体不可用

**Comment by jaykoboy** [comment]
更新到2.0.0还是提示“集成“colorfulclouds”不再提供此实体”
