### ISSUE TITLE
weather实体不会自动刷新

### ISSUE THREAD

**Issue by musk-1024** [fineemb/Colorfulclouds-weather#56]
weather实体不会自动刷新，需要对组件进行reload才可以手动刷新当前的日期，但是组件下其他的sensor刷新又是正常的，希望能解决一下
![image](https://github.com/fineemb/Colorfulclouds-weather/assets/83929038/b66313ab-f23f-4813-ae65-72cd1da53134)

**Comment by fineemb** [comment]
目测可能是ha的状态机机制。数据应该是定时刷新的。但是如果weather的状态和之前的数据一样。ha是不会更新的。不知道我有没有理解正确

**Comment by musk-1024** [comment]
> 目测可能是ha的状态机机制。数据应该是定时刷新的。但是如果weather的状态和之前的数据一样。ha是不会更新的。不知道我有没有理解正确

按照道理应该是定时刷新的，但是温度信息和天气信息是不一样也不会刷新，你这边是否能够复现这个问题？

**Comment by fineemb** [comment]
> > 目测可能是ha的状态机机制。数据应该是定时刷新的。但是如果weather的状态和之前的数据一样。ha是不会更新的。不知道我有没有理解正确
> 
> 按照道理应该是定时刷新的，但是温度信息和天气信息是不一样也不会刷新，你这边是否能够复现这个问题？

我大致知道是什么情况了。但是我没能复现。如果方便，可以在集成页面打开“启用调试日志”。
日志会根据你设置的刷新时间间隔打印`DEBUG (MainThread) [homeassistant.components.colorfulclouds.colorfulclouds] Requests remaining: `类似这样的条目

**Comment by fineemb** [comment]
这个问题已经在v2.0.3版本修复

**Comment by fineemb** [comment]
这个问题已经在v2.0.3版本修复
